### ISSUE TITLE
Some problems that may be caused by dependent library versions

### ISSUE THREAD

**Issue by sjnaj** [bd-iaas-us/infiniStore#22]
I don't know what your development environment and dependency library version is like, I encountered some problems during compilation and run, and finally did not successfully solve.
Q1:
` g++ -std=c++11 -Wall -g -I/usr/local/cuda/include -MMD -MP -fPIC -c libinfinity.cpp -o libinfinity.o
    In file included from libinfinity.cpp:16:
    ibv_helper.h:57:42: error: use of enum ‘ibv_gid_type’ without previous declaration
       57 |                 unsigned int index, enum ibv_gid_type *type);
          |                                          ^~~~~~~~~~~~
    ibv_helper.h:59:8: error: use of enum ‘ibv_gid_type’ without previous declaration
       59 |   enum ibv_gid_type gid_type, int gid_family);
          |        ^~~~~~~~~~~~
    libinfinity.cpp: In function ‘int init_rdma_resources(connection_t*)’:
    libinfinity.cpp:74:52: error: ‘IBV_GID_TYPE_ROCE_V2’ was not declared in this scope
       74 |     int gidx = ibv_find_sgid_type(conn->ib_ctx, 1, IBV_GID_TYPE_ROCE_V2, AF_INET);`

I solved  it by adding enum ibv_gid_type {IBV_GID_TYPE_IB,IBV_GID_TYPE_ROCE_V1，IBV_GID_TYPE_ROCE_V2，}；to  ibv_helper.h.

Q2:
`g++ -std=c++11 -Wall -g -I/usr/local/cuda/include -MMD -MP -fPIC -c utils.cpp -o utils.o
    utils.cpp: In function ‘void print_rdma_conn_info(rdma_conn_info_t*, bool)’:
    utils.cpp:47:57: error: cannot bind packed field ‘info->rdma_conn_info_t::gid.ibv_gid::raw[i]’ to ‘unsigned char&’
       47 |         gid_str += fmt::format("{:02x}", info->gid.raw[i]);
          |                                          ~~~~~~~~~~~~~~~^`

I solved  it by deleting packed attribute of rdma_conn_info_t.

Q3:

`>>> import infinity
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sgl-workspace/infiniStore/infinity/__init__.py", line 1, in <module>
    from .lib import (
  File "/sgl-workspace/infiniStore/infinity/lib.py", line 1, in <module>
    from infinity import _infinity
ImportError: cannot import name '_infinity' from partially initialized module 'infinity' (most likely due to a circular import) (/sgl-workspace/infiniStore/infinity/__init__.py)`

It seems like  casued by lib.py import the  infinity while  __init__.py import the lib.py.
I can import it by manually loading so library, but the functions inside are undefined,even if I use nm can see that function symbols exist.

I wonder if you know why I'm having these problems.

**Comment by thesues** [comment]
Q1:
the first may related to version of libibverbs-dev. 
```
# apt show libibverbs-dev
Package: libibverbs-dev
Version: 2307mlnx47-1.2310119
```

Q2:
this is due to the msgpack's version, do not delete packed attribute of rdma_conn_info_t
```
# apt info libmsgpack-dev
Package: libmsgpack-dev
Version: 3.0.1-3
```


I am working on packaging this daemon on pypi.

**Comment by sjnaj** [comment]
Thanks😊

**Comment by thesues** [comment]
you can re-test using `pip install infinistore` right now.

**Comment by sitabulaixizawaluduo** [comment]
> you can re-test using `pip install infinistore` right now.

It seems that the "circular import" problem still exists

**Comment by thesues** [comment]
> > you can re-test using `pip install infinistore` right now.
> 
> It seems that the "circular import" problem still exists
this is what I tested:
can you try this？ I am using [conda](https://docs.anaconda.com/miniconda/miniconda-install/)
```
conda create -n test python=3.11
conda activate test
pip install infinistore==0.1.72
python -m infinistore.server
```

can you paste the whole error message?

**Comment by liweiqing1997** [comment]
我也碰到了这个问题
(test) root@413a2f1c96d9:/mnt/data_disk101/infiniStore# 
 python -m infinistore.server
/root/miniconda3/envs/test/bin/python: Error while finding module specification for 'infinistore.server' (ImportError: cannot import name '_infinistore' from partially initialized module 'infinistore' (most likely due to a circular import)

**Comment by thesues** [comment]
make sure you have ```infinistore >= 0.1.74```, this version support python3.10, python3.11 and python3.12. other python version is not supported yet.
