### ISSUE TITLE
T4 GPU limitation? 

### ISSUE THREAD

**Issue by thesues** [bd-iaas-us/infiniStore#43]
Found an issue and need help:
https://github.com/bd-iaas-us/infiniStore/blob/main/infinistore/test_infinistore.py#L124

In this unit test, there are two ways of writing:

```python
src = torch.randn(size, device="cuda", dtype=torch.float32)
```
and

```python
src = torch.randn(size, dtype=torch.float32)  
src = src.cuda()
```

Logically, these two should behave the same, but using the former results in a write failure without throwing any error. It has the following characteristics:

1. The issue occurs with both local GPU and RDMA.
2. It's related to the tensor size. If the tensor is smaller than around 160MB, it works fine.
3. GPU hardware issue? I tried different versions of PyTorch.  the same result.

**Comment by XiaoningDing** [comment]
I think the first method will create the tensor directly in GPU, while the second one will create the tensor first in CPU and then copy it to GPU. But I don't know why there is a write failure with the first method.

**Comment by thesues** [comment]
the is because all torch APIs are async API. 
rand or randv operation is slow. it means even torch.rand returns,  the memory operation is not done yet.
so we have to add barrier ```torch.cuda.synchronize()``` before any kvcache.write. 

it explains why it only happens when  tensor is bigger.
