### ISSUE TITLE
Is 0.1.82 whl pkg updated? 

### ISSUE THREAD

**Issue by chenkaiyue** [bd-iaas-us/infiniStore#48]
I found that the code is still the former one, not the newest
![image](https://github.com/user-attachments/assets/b951cbb7-620f-4b73-8d5e-f7928e75b79b)
![image](https://github.com/user-attachments/assets/4e51397e-c6b4-46db-afb5-40a87f593f50)

**Comment by thesues** [comment]
only updated in main branch. Not released yet
