### ISSUE TITLE
Can infini use multi GPU?

### ISSUE THREAD

**Issue by chenkaiyue** [bd-iaas-us/infiniStore#49]
Can infini run on multi cards? When the requests pressure is high,  the bra1 memory is not enough.
![image](https://github.com/user-attachments/assets/7d5f817e-8656-4324-9546-e5c088505c1e)

![image](https://github.com/user-attachments/assets/7e62b61c-f750-4f7f-8a69-e01dc9e51cef)

**Comment by thesues** [comment]
I think we could wait a while when there is no available MR.  although waiting may slow down performance, but it is always better than raising exception.

**Comment by thesues** [comment]
since I changed API. if bar1 memory is less than GPU memory.  infinistore will quit and tell user GPU is not supported
