### ISSUE TITLE
RoCE IB support 

### ISSUE THREAD

**Issue by thesues** [bd-iaas-us/infiniStore#56]
I guess we should support RoCEv1 as well

**Comment by Luis-xu** [comment]
> I guess we should support RoCEv1 as well

Hi @thesues, 
I am trying to modify the RDMA initialization part to adapt to the **IB** protocol. Currently, I start the infiniStore service normally, and the basic write and read operations in the **client.py** file can be performed normally. However, at the end of the execution, **"ibv_poll_cq"** throws the following error:
![2024-10-28_16-16](https://github.com/user-attachments/assets/adaf4531-8cfd-4f29-a8a5-a3ac6c27ef24)
I don't know what caused the error.

**Comment by thesues** [comment]
when client connection is freed, a fake msg is send to cq_handler to have a gracefull stop.  maybe this is related?

you could comment out following lines, and try, 

![image](https://github.com/user-attachments/assets/f74262a7-f7da-4cc2-a02d-7efdd27e784e)
